language: python
dist: jammy
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "pypy3"
install:
  - pip install -r requirements.txt
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd .. && supybot-test UrbanDictionary
notifications:
  email: false
jobs:
  fast_finish: true
